server:
  port : 8081

spring:
  application:
    name: Game Service
  redis:
    host: localhost
    port: 6379

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

keepmygaming:
  game-operations-service:
    host: http://localhost:8082