spring:
  application:
    name: Keep My Gaming
  redis:
    host: localhost
    port: 6379

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG